### ISSUE TITLE
hbyteswp.h current master and develop branches 

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#461]
The current preprocessor logic prevents using the byteswap bultins when `NO_ASM_BYTESWAP` is set to 1.

IMO the correct sequence should be something along the lines of :

```
#if defined( HAVE_BYTESWAP_H )
   do nothing 
#elif defined( HAVE_SWAP_BUILTINS )
  use the builtins
#elif !defined( NO_ASM_BYTESWAP )
  use the RYO asm
#else 
  use c 
#endif
```

Happy New Year to everybody!

enrico

P.S. a simple "unifdef -DNO_ASM_BYTESWAP -B hbyteswp.h" command will show what I mean.

**Comment by Fish-Git** [comment]
`NO_ASM_BYTESWAP` is only defined _if and only if:_ the build architecture is _not_ x86, _**and**_ the system `byteswap.h` header is not found. That is to say, only when _both_ conditions are true _(not x86 architecture and system byteswap header not found)_ is `NO_ASM_BYTESWAP` ever defined.

But it appears you are wanting to use builtins on non-x86 build architectures even when the system `byteswap.h` header is not found? Is that correct?

While that certainly seems reasonable, I'm more interested in why your non-x86 build architecture is unable to locate the `byteswap.h` system header! It seems to me _that_ is the bug that needs to be fixed!

**Comment by atncsj6h** [comment]
Hi Fish,
that' s correct
I am on APPLE big sur, and APPLE does not provide byteswap.h ( and never did ) 

enrico

**Comment by Fish-Git** [comment]
Fixed by commit 8b20ae3acbeeab5cb30182b39e217cbcedd96998.

Closing.

**Comment by wrljet** [comment]
Fish,

What is causing these extra commits?  Such as:

`Merge branch 'develop' of https://github.com/SDL-Hercules-390/hyperion into develop`

Bill

**Comment by Fish-Git** [comment]
> What is causing these extra commits? Such as:
> 
> `Merge branch 'develop' of https://github.com/SDL-Hercules-390/hyperion into develop`

Someone (i.e. ME!) forgetting to do a git pull to merge recent updates (commits) into one's local repository (to bring it current) before committing ones own changes. When that happens, ones local repository becomes "out of sync" with the remote, preventing one from being able to push their commit. Instead, one must first do a pull to merge the remote repository's commit into ones local repository and _then_ push the results to the remote (which, due the commits being applied "out of sequence" in ones local repository, causes a "merge" to occur when one pushes their commit).

I don't know what git client you personally use, but I use TortoiseGit (a GUI git client) and its commit log illustrates what has actually happened when such a situation occurs:

![TortoiseGit-Log](https://user-images.githubusercontent.com/1486786/152619390-2d8148c2-dd48-40d1-962e-fba2d50eb88e.jpg)

As you can see, you actually made your commit and pushed it to the remote _before_ I committed my changes to _my_ local repository. (i.e. I failed to do a 'pull' to merge your changes into my local repository _before_ I committed my own changes to my local repository).

As a result, after I did my commit (without doing a pull first), _my_ local repository got "out of sync" with "reality" (with the remote). So when I eventually did my pull (to bring your changes into my local), your commit ended up being committed physically _after_ my own commit, when in actuality it _should_ have been the exact opposite. _(Your commit was actually made logically before my commit, not after!)_

Thus when the push occurred (to push my changes to the remote), git had to basically temporarily undo your commit so that it could them apply my commit, and then afterwards, merge your commit back into the repository again to keep everything in sync.

As I said, it's me basically being forgetful/lazy, forgetting to always do a pull before committing my own changes to my local repository (to ensure my local repository matches the remote before I make my own commit). Sorry!

No damage occurs whatsoever. It's actually not that big of a deal. It's something that occasionally happens when there are multiple people working with the same repository. Such occurrences can _still_ nevertheless  occur even when one is careful to always do a pull beforehand:

1. You have uncommitted changes you want to commit.
2. You properly do a pull beforehand to bring your local repository current with the remote.
3. You commit your changes to your local repository.
4. You try pushing your commit to the remote, but...
5. Git complains that your local doesn't match the remote!
6. So you do yet _another_ pull and discover yet another commit (that someone pushed just a split second ago) that your local didn't have (which is then added to your local repository too, but physically _after_ your commit instead of _before_ it).
7. You finally try your push again, and _this_ time it works okay, but of course results in git having to do an automatic "Merge commit" in order to get the commits back into their proper sequence.

Does that make sense?

**Comment by Fish-Git** [comment]
> Thus when the push occurred (to push my changes to the remote), git had to basically temporarily undo your commit so that it could then apply my commit, and then afterwards, merge your commit back into the repository again to keep everything in sync.

_Actually_, what I think actually happens is, git create a temporary internal "merge branch" anchored at the point immediately prior to your commit (since that's what _my_local looked like when I made my local commit). commits my changes to that temporary branch, and then afterwards, automatically "merges" that temporary branch into the main branch.

That is to say, I don't think it does an "undo" of your commit before it commits my changes. Rather it simply creates an internal branch and commits my changes to that temporary branch and then automatically merges the changes in that temporary branch back into the main branch. That's what I think is actually happening.

But the idea is the same: it needs to juggle things around so that the commits get applied to the repository in the correct sequence.

**Comment by wrljet** [comment]
Fish,

Yes, it makes sense now that you've explained it.
I'm one of those oldtimers who still doesn't _get_ git. :-)

I will give TortoiseGit a try.  I've been trying to do most of my commits via command line in *Nix,
after having GitHub Desktop (for Windows) goof up the permission bits a few times.

Bill

**Comment by Fish-Git** [comment]
> I will give TortoiseGit a try.

If, after installing it, you need any help with configuring it or using it, let me know. I've been using it for years.

**Comment by Fish-Git** [comment]
p.s. It also helps to have a good visual comparison tool installed too, such as [**ExamDiff Pro**](https://www.prestosoft.com/edp_examdiffpro.asp). When you do, viewing commits becomes trivially easy. (and fun!) I learn a lot by reviewing other people's commits.

It also makes it much easier to review your own changes before you commit them too. I personally couldn't image doing any type of serious software development without having something like ExamDiff Pro installed. I mean that seriously. It's a tool that IMO should be in _every_ programmer's tool box.

I can help you with setting _it_ up (configuring it) too. With its plethora of options it can be quite intimidating to the first time user. Getting the toolbar (and a few default comparison options) set up right is essential IMO. Once you have that set up, 99% of what you normally do is either just a simple double-click or a click of a toolbar button.

**Comment by wrljet** [comment]
Fish,

> p.s. It also helps to have a good visual comparison tool installed too, such as [**ExamDiff Pro**](https://www.prestosoft.com/edp_examdiffpro.asp). When you do, viewing commits becomes trivially easy. (and fun!) I learn a lot by reviewing other people's commits.

I've been using **WinMerge** since Jesus was a small boy.
But it's not all that actively developed/supported anymore.

Bill
